apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.app.name }}-svc
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "sticky-resource-master"
spec:
  ports:
  - port: {{ .Values.app.port }}
    name: http
  selector:
    app: {{ .Values.app.name }}-depl
  type: ClusterIP
