apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.app.name }}-svc
spec:
  ports:
  - port: {{ .Values.app.port }}
    name: http
  selector:
    app: {{ .Values.app.name }}-depl
  type: ClusterIP
