apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-depl
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-depl
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-depl
    spec:
      containers:
      - name: {{ .Values.app.name }}-depl
        image: ghcr.io/topinvestor4000/resourcemaster:{{ .Values.app.tag }}
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: {{ .Values.app.port }}
        resources:
          limits:
            memory: 2Gi
            cpu: 1
          requests:
            memory: 2Gi
            cpu: 1
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.name }}-creds
              key: user
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.name }}-creds
              key: db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.name }}-creds
              key: password
