apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.name }}-creds
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  user: postgres
  db: resourcemaster
  password: {{ .Values.db.password | b64enc }}
