apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sonar.name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.sonar.name }}-svc
spec:
  ports:
  - port: {{ .Values.sonar.port }}
    name: sonar
  selector:
    app: {{ .Values.sonar.name }}-depl
  type: ClusterIP
