# .github/workflows/deploy.yml
name: Deploy Prod
on:
  workflow_run:
    workflows: ["Build and test"]
    branches: [master]
    types: 
      - completed
  workflow_dispatch:

jobs:
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Install Helm'
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
      shell: bash

    - name: 'Install Kubectl'
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
        echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      shell: bash

    - name: 'Put KUBECONFIG'
      run: |
        mkdir -p ~/.kube/
        echo '${{ secrets.KUBE_CONFIG }}' > ~/.kube/config
      shell: bash

    - name: 'Apply manifests'
      run: |
        cd deploy
        helm template -f values-prod.yaml --set db.password=${{ secrets.PRODUCTION }} . | kubectl apply -f -
      shell: bash

    - name: 'Rollout restart'
      run: |
        kubectl rollout restart deploy -n resourcemaster-prod
      shell: bash
